### ISSUE TITLE
customizeUI.listRowHeight  Dislocation of position

### ISSUE THREAD

**Issue by qingweiSun** [iocave/customize-ui#16] opened 2019-12-17 05:19 UTC

**Comment by knopp** [comment] 2019-12-17 09:19
I'm not sure what exactly is the problem here. Can you provide screenshot and complete vscode version?

**Comment by qingweiSun** [comment] 2020-01-03 01:11
![image](https://user-images.githubusercontent.com/16513906/71702175-e54f0a80-2e08-11ea-9b50-f357851bac84.png)

版本: 1.42.0-insider
提交: 7c0095ee2d064033fc13184127a9adc603454729
日期: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by knopp** [comment] 2020-01-03 10:14
What are your customize-ui settings? What's the icon theme? I can not seem to be able to reproduce this.

**Comment by forivall** [comment] 2020-02-14 08:32
Looks like a duplicate of #26 ?

**Closed** 2020-05-18 05:49 UTC
