### ISSUE TITLE
Frameless title bar no longer working

### ISSUE THREAD

**Issue by danrocha** [iocave/customize-ui#149] opened 2022-09-19 06:31 UTC
I believe the following settings combination are no longer working:

```json
"window.titleBarStyle": "native",
"customizeUI.titleBar": "frameless",
```

VSCode Insiders (September 1.72)

Anyone else?

**Comment by danrocha** [comment] 2022-09-20 08:13
Yes. Updated 5 days ago.

**Comment by roycastro** [comment] 2022-09-21 07:41
Hey @knopp, thanks for supporting this plugin.
I'm also getting the described behavior with the following setup:

> **Customize UI:** 
v0.1.64
**Monkey Patch**
v0.1.19
**Visual Studio Code:**
Version: 1.72.0-insider
Commit: 333754f29b719f605904f072b13c054c2231b9bd
Date: 2022-09-21T05:40:07.654Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.4.0
Sandboxed: Yes

**Comment by knopp** [comment] 2022-09-21 11:01
Sadly I can't reproduce this.

<img width="250" alt="Screenshot 2022-09-21 at 13 00 05" src="https://user-images.githubusercontent.com/96958/191487623-dbb4eb48-b742-4f0e-b47c-c12d39ea1fed.png">

Can you post here content of `/Users/<your-folder>/Library/Application Support/Code - Insiders/User/globalStorage/iocave.monkey-patch/modules/main.js` ?

**Comment by roycastro** [comment] 2022-09-21 13:16
Sure @knopp, here it's.
main.js
`require.config({
    paths: {
        "customize-ui" : "/Users/myuser/Library/Application Support/Code - Insiders/User/globalStorage/iocave.customize-ui/modules",
        "monkey-generated" : "/Users/myuser/Library/Application Support/Code - Insiders/User/globalStorage/iocave.monkey-patch/modules"
    }
});

define(["monkey-generated/entrypoint-main", "customize-ui/title-bar-main-process", "customize-ui/utils"], function (){});`

**Comment by danrocha** [comment] 2022-09-23 08:59
Here is it:

```js
require.config({
    paths: {
        "customize-ui" : "/Users/danieldarocha/Library/Application Support/Code - Insiders/User/globalStorage/iocave.customize-ui/modules",
        "monkey-generated" : "/Users/danieldarocha/Library/Application Support/Code - Insiders/User/globalStorage/iocave.monkey-patch/modules"
    }
});

define(["monkey-generated/entrypoint-main", "customize-ui/title-bar-main-process", "customize-ui/utils"], function (){});
```

**Comment by knopp** [comment] 2022-09-25 08:55
I was able to reproduce this after clean reinstall. I pushed updates for both customize-ui and monkey patch. It should work with latest stable (1.71.2), but insiders currently has a bug where the amd-loader is not used. I believe this is going to get fixed in vscode so I don't want to add additional workarounds in monkey-patch for that.

If you want to get customize-ui working with latests insiders you can try the following:
Edit `Visual Studio Code - Insiders.app/Contents/Resources/app/out/main.js` and replace `require_bootstrap_amd()` with `require('./bootstrap-amd')`.

**Comment by knopp** [comment] 2022-09-25 09:26
Actually, I was reading the code wrong. This part works as expected. I have pushed monkey-patch@0.1.21 which should do the step automatically.

**Comment by danrocha** [comment] 2022-09-26 08:40
I can confirm it is working now! Thank you @knopp

**Closed** 2022-09-26 08:40 UTC
